### ISSUE TITLE
Add hover effect to the search button

### ISSUE THREAD

**Issue by harshsbhandari** [elliotwutingfeng/meteorite-explorer#522]
Add hover effect to the search button. I can fix that, please assingn this to me @elliotwutingfeng.
![Uploading Screenshot (160).png…]()

**Comment by elliotwutingfeng** [comment]
What needs fixing on the search button?

**Comment by harshsbhandari** [comment]
> What needs fixing on the search button?

Adding the zoom in effect on hovering over it and color change effect on clicking the button

**Comment by elliotwutingfeng** [comment]
Thanks for the suggestion but I think the button's aesthetics is fine as it is.
